apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: deployment-ns
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: nginx:latest
