apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kishu-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: kishu-container1
        image: nginx:1.14.2
        ports:
        - containerPort: 80 



